name: Assign work in progress label when pull request is updated
on: [pull_request]
jobs:
  working_label:
    runs-on: ubuntu-latest
    name: Label working progress
    steps:
      - uses: AlbertHernandez/working-label-action@dev
        with:
          work_in_progress_label: 'Work in progress'
          ready_to_review_label: 'Ready to review'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
